### PR TITLE
sqlite3: fix building

### PR DESCRIPTION
**Pull request by ShevT**
Maybe not quite the correct patch, but an error here.

### CODE REVIEW

**Comment by temasek** [comment]
What device failed?

**Comment by ShevT** [comment]
This is [my device](https://github.com/ShevT/device_huawei_U9500/tree/temasek-lp).

He is not in the repo.
And what's the difference?

**Comment by temasek** [comment]
Exactly I should ask, whats the diff? I have no problem compiling.

**Comment by ShevT** [comment]
Oops. Sorry. I used this sqlite to build Mokee.
Maybe that's the problem.
I'll check on temasek

**Comment by ShevT** [comment]
Error: external/sqlite/dist/sqlite3.c:18536:19: error: operator '&&' has no left operand
The same error during assembly temasek 5.1.1

**Comment by temasek** [comment]
Oh.....its cm12.1. I thought I saw cm13.0. OK to merge.

**Comment by ShevT** [comment]
It does not work, but it is compiled.
It seems that something has to be [like this](https://github.com/temasek/android_external_sqlite/blob/cm-12.1/dist/Android.patch).

**Comment by ShevT** [comment]
I do likewise [here that](https://github.com/temasek/android_external_sqlite/commit/be3c8d1db6811472c00ab97712b710bf9a68d0a0).
If successfully working, I'll tell you. Commits [here](https://github.com/ShevT/android_external_sqlite/commits/cm-12.1).

**Comment by ShevT** [comment]
Yes! It works!
Please remove my patch (git reset --hard HEAD ^)
and I will make a new pull request. 
Or collect 2 patch from [my repo](https://github.com/ShevT/android_external_sqlite/commits/cm-12.1)

**Pull request merged**
